/** Three 装配单 that bind to SAMPLE_TABLE (test/variable-table-sample.ts). Kept in one place so every stage-2 test compiles the same sheets. */
export const STATUS_SHEET = [
  '前端: 状态栏',
  '形态: placeholder',
  '预设: sakura',
  '标题: 样卡',
  '折叠: true',
  '摘要:',
  '  - 变量: /主角/生命',
  '    显示: 生命',
  '  - 变量: /主角/状态',
  '分页:',
  '  - 名称: 状态',
  '    图标: heart',
  '    区块:',
  '      - 类型: stats',
  '        标题: 主角',
  '        项:',
  '          - 变量: /主角/姓名',
  '            显示: 姓名',
  '          - 变量: /主角/生命',
  '          - 变量: /主角/状态',
  '          - 变量: /主角/在逃',
  '      - 类型: bars',
  '        项:',
  '          - 变量: /主角/生命',
  '            显示: 生命',
  '      - 类型: crisis',
  '        变量: /主角/生命',
  '        档位:',
  '          - { 至: 30, 名称: 濒死, 色: danger }',
  '          - { 至: 70, 名称: 受伤, 色: warn }',
  '          - { 名称: 安好, 色: ok }',
  '  - 名称: 人物',
  '    图标: users',
  '    区块:',
  '      - 类型: relation',
  '        变量: /人物',
  // {键} is a flow indicator inside a flow mapping, so the pointer values are quoted here (the block-context 进度 line needs no quotes).
  "        字段: { 好感: '/人物/{键}/好感', 所在: '/人物/{键}/所在' }",
  '        进度: /人物/{键}/好感',
  '      - 类型: tags',
  '        标题: 货币',
  '        变量: /货币',
  '  - 名称: 记录',
  '    图标: scroll',
  '    区块:',
  '      - 类型: timeline',
  '        变量: /事件记录',
  '        最近: 4',
  '      - 类型: fold',
  '        标题: 任务',
  '        区块:',
  '          - 类型: list',
  '            变量: /任务',
  '            字段: { 标题: /任务/-/标题 }',
  '      - 类型: delta',
  '        项: [{ 变量: /主角/生命, 显示: 生命 }]',
  '      - 类型: text',
  '        文本: 记录只显示最近几条。',
  '      - 类型: custom',
  '        HTML: \'<div class="cw-seal">样卡</div>\'',
  '        CSS: \'.cw-seal { color: var(--accent); border: 1px solid var(--line); border-radius: var(--radius-sm); padding: 2px 8px; }\'',
  '',
].join('\n');

export const BODY_SHEET = [
  '前端: 正文美化',
  '预设: sakura',
  '根标签: content',
  '楼层: 10',
  '状态头: false',
  '模块:',
  '  - 标签: time',
  '    角色: 页眉',
  '  - 标签: story',
  '    角色: 正文',
  '  - 标签: now_plot',
  '    角色: 折叠',
  '    显示: 当前剧情',
  '自定义区块:',
  '  - HTML: \'<p class="cw-note">本卡由样卡工坊制作。</p>\'',
  '    CSS: \'.cw-note { color: var(--text-3); font-size: 12px; }\'',
  '',
].join('\n');

export const START_SHEET = [
  '前端: 创角页',
  '预设: sakura',
  '标题: 样卡 · 入港登记',
  '步骤:',
  '  - 名称: 身份',
  '    字段:',
  '      - 键: 姓名',
  '        类型: 文本',
  '        必填: true',
  '        提示: 你的名字',
  '        写入: /主角/姓名',
  '      - 键: 状态',
  '        类型: 单选',
  '        选项: [正常, 受伤]',
  '        写入: /主角/状态',
  '      - 键: 生命',
  '        类型: 滑杆',
  '        范围: [1, 100]',
  '        写入: /主角/生命',
  '  - 名称: 关系',
  '    字段:',
  '      - 键: 熟人',
  '        类型: 人物列表',
  '        选项: [林砚, 老周]',
  '        最多: 2',
  '  - 名称: 自定义开局',
  '    自定义开局: true',
  '    字段:',
  '      - { 键: 补充, 类型: 长文本, 提示: 想加什么都写在这里 }',
  '写入:',
  '  世界书条目:',
  '    名称: \'[样卡] 初始人物设定\'',
  '    模板: |',
  '      玩家：{姓名}，状态{状态}，生命{生命}。熟人：{熟人}。',
  '      {补充}',
  '  开场信息: |',
  '    （{姓名}走进港口）',
  '  初始变量: true',
  '',
].join('\n');
