import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, readFile, readdir, writeFile, rm, copyFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import { UpdateService } from '../src/main/updates.ts';

const exec=promisify(execFile),digest=(data:Buffer|string)=>createHash('sha256').update(data).digest('hex');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'cardwright-updates-'));const data=join(root,'data'),source=join(root,'source');await mkdir(data);await mkdir(source);await writeFile(join(data,'state.json'),JSON.stringify({version:'old',tasks:[]}));await writeFile(join(data,'studio.json'),JSON.stringify({rules:['old']}));return{root,data,source,async cleanup(){assert.equal(dirname(root),resolve(tmpdir()));assert.match(root,/cardwright-updates-/);await rm(root,{recursive:true,force:true});}};}
async function updateFile(source:string,version='0.8.0'){const file=`Cardwright-Setup-${version}.exe`,bytes=Buffer.from('MZ test fixture installer; never execute');await writeFile(join(source,file),bytes);const manifest={app:'Cardwright',version,file,sha256:digest(bytes)};const path=join(source,'cardwright-update.json');await writeFile(path,JSON.stringify(manifest));return{path,manifest,bytes};}

test('local updates verify checksum and version, preserve state/studio and reject changed packages',async()=>{
  const f=await fixture();try{const item=await updateFile(f.source),service=new UpdateService(f.data,'0.7.0');await mkdir(service.root,{recursive:true});await writeFile(join(service.root,'Cardwright-0.7.0.exe'),'OLD_INSTALLER');assert.equal((await service.import(item.path)).status,'ready');await service.prepareInstall();assert.deepEqual(JSON.parse(await readFile(join(service.root,'backups','studio-0.7.0.json'),'utf8')),{rules:['old']});
    await writeFile(join(f.data,'state.json'),JSON.stringify({version:'new'}));await writeFile(join(f.data,'studio.json'),JSON.stringify({rules:['new']}));assert.equal(await service.prepareRollback(),join(service.root,'Cardwright-0.7.0.exe'));assert.equal(JSON.parse(await readFile(join(f.data,'state.json'),'utf8')).version,'old');assert.deepEqual(JSON.parse(await readFile(join(f.data,'studio.json'),'utf8')),{rules:['old']});
    await writeFile(service.state().path!,'TAMPERED');await assert.rejects(service.prepareInstall(),/changed/);
    const older=await updateFile(f.source,'0.6.0');await assert.rejects(service.import(older.path),/newer/);
  }finally{await f.cleanup();}
});

test('update manifest file names cannot escape their source folder',async()=>{const f=await fixture();try{const item=await updateFile(f.source),service=new UpdateService(f.data,'0.7.0');for(const file of ['../bad.exe','..\\bad.exe','C:\\bad.exe','a.exe:stream','CON.exe']){await writeFile(item.path,JSON.stringify({...item.manifest,file}));await assert.rejects(service.import(item.path),/valid Cardwright/);}await writeFile(item.path,JSON.stringify({...item.manifest,sha256:'0'.repeat(64)}));await assert.rejects(service.import(item.path),/checksum/);}finally{await f.cleanup();}});

test('update preflight is read-only and missing rollback caches leave the live profile intact',async()=>{const f=await fixture();try{const service=new UpdateService(f.data,'0.7.0'),beforeState=await readFile(join(f.data,'state.json')),beforeStudio=await readFile(join(f.data,'studio.json')),beforeFiles=await readdir(f.data);await assert.rejects(service.validateInstall(),/Import a valid update/);await assert.rejects(service.validateRollback(),/No previous installer/);assert.deepEqual(await readdir(f.data),beforeFiles);assert.deepEqual(await readFile(join(f.data,'state.json')),beforeState);assert.deepEqual(await readFile(join(f.data,'studio.json')),beforeStudio);const update=await updateFile(f.source);await service.import(update.path);await service.validateInstall();await assert.rejects(readFile(join(service.root,'backups','state-0.7.0.json')),{code:'ENOENT'});await writeFile(join(service.root,'Cardwright-0.7.0.exe'),'old installer');await service.prepareInstall();await writeFile(join(f.data,'state.json'),'  {"newState":true}\n');await writeFile(join(f.data,'studio.json'),' {"newStudio":true}\n');await service.validateRollback();assert.equal(await readFile(join(f.data,'state.json'),'utf8'),'  {"newState":true}\n');assert.equal(await readFile(join(f.data,'studio.json'),'utf8'),' {"newStudio":true}\n');}finally{await f.cleanup();}});

test('HTTPS update feed requires a same-origin nonredirecting package and bounds manifests',async()=>{
  const f=await fixture();try{const item=await updateFile(f.source);let calls=0;const fake:typeof fetch=async(_input,options)=>{assert.equal(options?.redirect,'error');calls++;return calls===1?new Response(JSON.stringify(item.manifest)):new Response(item.bytes);};const service=new UpdateService(f.data,'0.7.0',fake);await assert.rejects(service.check('http://updates.example/feed.json'),/HTTPS/);assert.equal((await service.check('https://updates.example/feed.json')).status,'ready');assert.equal(calls,2);
    const cross:typeof fetch=async()=>new Response(JSON.stringify({...item.manifest,url:'https://other.example/package.exe'}));await assert.rejects(new UpdateService(f.data,'0.7.0',cross).check('https://updates.example/feed.json'),/origin/);
    const redirect:typeof fetch=async()=>new Response(null,{status:302,headers:{location:'https://other.example'}});await assert.rejects(new UpdateService(f.data,'0.7.0',redirect).check('https://updates.example/feed.json'),/redirected/);
    const huge:typeof fetch=async()=>new Response('x'.repeat(64001));await assert.rejects(new UpdateService(f.data,'0.7.0',huge).check('https://updates.example/feed.json'),/too large/);
    const older:typeof fetch=async()=>new Response(JSON.stringify({...item.manifest,version:'0.6.0'}));assert.equal((await new UpdateService(f.data,'0.7.0',older).check('https://updates.example/feed.json')).status,'idle');
  }finally{await f.cleanup();}
});

test('rollback refuses outside installers and invalid data before replacing current state',async()=>{const f=await fixture();try{const service=new UpdateService(f.data,'0.7.0');await mkdir(service.root);const outside=join(f.root,'outside.exe');await writeFile(outside,'BAD');await writeFile(join(service.root,'rollback.json'),JSON.stringify({path:outside,sha256:digest('BAD'),version:'0.6.0'}));await assert.rejects(service.prepareRollback(),/verified/);assert.equal(JSON.parse(await readFile(join(f.data,'state.json'),'utf8')).version,'old');await mkdir(join(service.root,'backups'));const old=join(service.root,'Cardwright-0.6.0.exe');await writeFile(old,'OLD');await writeFile(join(service.root,'rollback.json'),JSON.stringify({path:old,sha256:digest('OLD'),version:'0.6.0'}));await writeFile(join(service.root,'backups','state-0.6.0.json'),'not json');await assert.rejects(service.prepareRollback(),/compatible/);assert.equal(JSON.parse(await readFile(join(f.data,'state.json'),'utf8')).version,'old');}finally{await f.cleanup();}});

test('rollback restores matching encrypted credentials and refuses legacy snapshots without a credential receipt',async()=>{const f=await fixture();try{const service=new UpdateService(f.data,'0.7.0');await writeFile(join(f.data,'credentials.enc.json'),'OLD_CIPHERTEXT');const item=await updateFile(f.source);await service.import(item.path);await writeFile(join(service.root,'Cardwright-0.7.0.exe'),'old installer');await service.prepareInstall();await writeFile(join(f.data,'state.json'),JSON.stringify({gateway:'new-url'}));await writeFile(join(f.data,'credentials.enc.json'),'NEW_CIPHERTEXT');await service.prepareRollback();assert.equal(await readFile(join(f.data,'credentials.enc.json'),'utf8'),'OLD_CIPHERTEXT');assert.equal(await readFile(join(service.root,'backups','credentials-before-rollback.enc.json'),'utf8'),'NEW_CIPHERTEXT');await rm(join(service.root,'backups','credentials-0.7.0.receipt.json'));await assert.rejects(service.validateRollback(),/credential snapshot/);assert.equal(await readFile(join(f.data,'credentials.enc.json'),'utf8'),'OLD_CIPHERTEXT');}finally{await f.cleanup();}});

test('an explicitly empty credential snapshot clears newer credentials on rollback',async()=>{const f=await fixture();try{const service=new UpdateService(f.data,'0.7.0'),item=await updateFile(f.source);await service.import(item.path);await writeFile(join(service.root,'Cardwright-0.7.0.exe'),'old installer');await service.prepareInstall();await writeFile(join(f.data,'credentials.enc.json'),'NEW_CIPHERTEXT');await service.prepareRollback();await assert.rejects(readFile(join(f.data,'credentials.enc.json')),{code:'ENOENT'});assert.equal(await readFile(join(service.root,'backups','credentials-before-rollback.enc.json'),'utf8'),'NEW_CIPHERTEXT');}finally{await f.cleanup();}});

async function compile(path:string,body:string){const source=`using System;using System.IO;class Fixture { static int Main() { ${body} } }`;const file=`${path}.cs`;await writeFile(file,source);await exec(join(process.env.SystemRoot||'C:\\Windows','Microsoft.NET','Framework64','v4.0.30319','csc.exe'),['/nologo','/target:exe',`/out:${path}`,file],{windowsHide:true});}
const csharp=(path:string)=>`@"${path.replaceAll('"','""')}"`;
async function supervise(kind:'success'|'installer-failure'|'health-failure'|'tamper'){
  const f=await fixture();const updates=join(f.data,'updates'),target=join(f.root,'installation');await mkdir(updates);await mkdir(target);await mkdir(join(updates,'backups'));const oldState=join(updates,'backups','state-0.7.0.json'),oldStudio=join(updates,'backups','studio-0.7.0.json');await writeFile(oldState,JSON.stringify({version:'compatible'}));await writeFile(oldStudio,JSON.stringify({rules:['compatible']}));
  const credentialsBackup=join(updates,'backups','credentials-0.7.0.enc.json'),credentialsReceipt=join(updates,'backups','credentials-0.7.0.receipt.json');await writeFile(credentialsBackup,'OLD_CIPHERTEXT');await writeFile(credentialsReceipt,JSON.stringify({format:1,present:true,sha256:digest('OLD_CIPHERTEXT')}));await writeFile(join(f.data,'credentials.enc.json'),'NEW_CIPHERTEXT');
  const healthy=join(f.root,'healthy.exe'),app=join(target,'Cardwright.exe'),installer=join(updates,'Cardwright-0.8.0.exe'),previous=join(updates,'Cardwright-0.7.0.exe');
  await compile(healthy,'File.WriteAllText(Environment.GetEnvironmentVariable("CARDWRIGHT_UPDATE_HEALTH_FILE"),Environment.GetEnvironmentVariable("CARDWRIGHT_UPDATE_HEALTH_TOKEN"));return 0;');
  await compile(installer,kind==='installer-failure'?'return 42;':'return 0;');await compile(previous,`File.Copy(${csharp(healthy)},${csharp(app)},true);File.WriteAllText(Path.Combine(Environment.GetEnvironmentVariable("CARDWRIGHT_DATA_DIR"),"previous-installed.txt"),"yes");return 0;`);
  if(kind==='health-failure')await compile(app,'return 9;');else await copyFile(healthy,app);
  const parent=spawn(process.execPath,['-e','setTimeout(()=>{},200)'],{windowsHide:true,stdio:'ignore'});await new Promise<void>((done,reject)=>{parent.once('spawn',done);parent.once('error',reject);});
  const reportPath=join(updates,'report-fixture.json'),jobPath=join(updates,'job-fixture.json');const job={format:1,action:'install',parentPid:parent.pid,dataDir:f.data,installer:{path:installer,sha256:digest(await readFile(installer))},previous:{path:previous,sha256:digest(await readFile(previous))},backup:oldState,studioBackup:oldStudio,credentialsBackup,credentialsReceipt,targetDirectory:target,executable:app,healthFile:join(updates,'health-fixture.txt'),healthToken:'fixture-health-token-1234567890',reportPath,healthTimeoutMs:1500,installerTimeoutMs:10000};await writeFile(jobPath,JSON.stringify(job));if(kind==='tamper')await writeFile(installer,'tampered');
  try{const result=await exec(resolve('dist/Cardwright.UpdateHost.exe'),[jobPath],{windowsHide:true,timeout:20000}).catch(error=>error as {code:number});return{kind,result,report:JSON.parse(await readFile(reportPath,'utf8')),state:JSON.parse(await readFile(join(f.data,'state.json'),'utf8')),studio:JSON.parse(await readFile(join(f.data,'studio.json'),'utf8')),credentials:await readFile(join(f.data,'credentials.enc.json'),'utf8')};}finally{parent.kill();await f.cleanup();}
}

test('native update supervisor accepts a healthy installed app in an isolated fixture',{skip:process.platform!=='win32'},async()=>{const run=await supervise('success');assert.equal(run.report.status,'installed');assert.equal(run.state.version,'old');});
test('native update supervisor restores installer, data and matching ciphertext on installer failure',{skip:process.platform!=='win32'},async()=>{const run=await supervise('installer-failure');assert.equal(run.report.status,'rolled_back');assert.equal(run.state.version,'compatible');assert.deepEqual(run.studio,{rules:['compatible']});assert.equal(run.credentials,'OLD_CIPHERTEXT');});
test('native update supervisor rolls back failed startup and refuses changed installers',{skip:process.platform!=='win32'},async()=>{const failed=await supervise('health-failure');assert.equal(failed.report.status,'rolled_back');assert.equal(failed.state.version,'compatible');assert.equal(failed.credentials,'OLD_CIPHERTEXT');const tamper=await supervise('tamper');assert.equal(tamper.report.status,'failed');assert.equal(tamper.state.version,'old');assert.equal(tamper.credentials,'NEW_CIPHERTEXT');});
