module.exports = {
  appId: 'com.cardwright.desktop',
  productName: 'Cardwright',
  asar: false,
  npmRebuild: false,
  buildDependenciesFromSource: false,
  directories: { buildResources: 'build-resources' },
  files: ['dist/**/*', 'package.json', 'package-lock.json', 'node_modules/**/*', 'LICENSE*', 'THIRD_PARTY*', '!release/**/*', '!artifacts/**/*', '!test/**/*', '!src/**/*'],
  win: { target: ['nsis', 'zip'], executableName: 'Cardwright', artifactName: 'Cardwright-${version}-win-x64.${ext}', signAndEditExecutable: false, signExecutable: false, verifyUpdateCodeSignature: false },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'Cardwright',
    deleteAppDataOnUninstall: false,
    runAfterFinish: false,
    include: 'build-resources/installer.nsh',
    artifactName: 'Cardwright-Setup-${version}.exe',
  },
  publish: null,
};
