import { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, LoaderCircle, Plus, RefreshCw, Search, Star, Trash2 } from 'lucide-react';
import type { Gateway, GatewayModel, ThinkingLevel } from '../shared/types';
import { gatewayModels } from '../shared/gateway-models';
import { useApp } from './context';
import { Field, IconButton, Modal } from './primitives';
import { thinkingLabel, thinkingLevels } from './effort';
import { defaultEffortMap } from '../shared/effort';
import { DEFAULT_MAX_OUTPUT_TOKENS } from '../shared/output-limit';

const blankModel = (id: string, name?: string): GatewayModel => ({ id, ...(name && name !== id ? { name } : {}), reasoning: false, effortMap: { ...defaultEffortMap }, contextWindow: 300000, maxTokens: DEFAULT_MAX_OUTPUT_TOKENS });

export function GatewayEditor({ gateway, onClose }: { gateway?: Gateway; onClose: () => void }) {
  const { api, t, run } = useApp();
  const [connection, setConnection] = useState(gateway ? { id: gateway.id, name: gateway.name, baseUrl: gateway.baseUrl, protocol: gateway.protocol } : { id: crypto.randomUUID(), name: '', baseUrl: '', protocol: 'openai-completions' as Gateway['protocol'] });
  const [models, setModels] = useState<GatewayModel[]>(() => gateway ? gatewayModels(gateway).map(model => ({ ...model, effortMap: { ...defaultEffortMap, ...model.effortMap, ultra: 'max' } })) : []);
  const [defaultId, setDefaultId] = useState(gateway?.modelId || '');
  const [selectedId, setSelectedId] = useState(gateway?.modelId || '');
  const [key, setKey] = useState(''); const [busy, setBusy] = useState(false);
  const [catalog, setCatalog] = useState<Array<{ id: string; name?: string }>>([]);
  const [fetching, setFetching] = useState(false); const [modelError, setModelError] = useState(''); const [loaded, setLoaded] = useState(false);
  const [catalogOpen, setCatalogOpen] = useState(!gateway); const [query, setQuery] = useState(''); const [selectedCatalog, setSelectedCatalog] = useState<string[]>([]);
  const [manualId, setManualId] = useState(''); const [formError, setFormError] = useState('');
  const request = useRef(0); const active = models.find(model => model.id === selectedId);
  const validConnection = /^https?:\/\/[^\s]+$/i.test(connection.baseUrl.trim()) && (!!key.trim() || !!gateway?.hasKey);
  const shownCatalog = catalog.filter(model => `${model.id} ${model.name || ''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const existing = new Set(models.map(model => model.id));
  async function fetchModels() {
    if (!validConnection) return; const sequence = ++request.current; setFetching(true); setModelError('');
    try { const result = await api.fetchModels({ ...(gateway ? { id: gateway.id } : {}), baseUrl: connection.baseUrl.trim(), protocol: connection.protocol }, key || undefined); if (sequence !== request.current) return; setCatalog(result); setLoaded(true); }
    catch { if (sequence === request.current) { setCatalog([]); setLoaded(false); setModelError(t('The model list could not be loaded. Check the connection or add model IDs below.', '未能读取模型列表。请检查连接，或在下方手动添加模型 ID。')); } }
    finally { if (sequence === request.current) setFetching(false); }
  }
  useEffect(() => { request.current++; setCatalog([]); setSelectedCatalog([]); setLoaded(false); setModelError(''); setFetching(false); if (!validConnection) return; const timer = setTimeout(() => void fetchModels(), 800); return () => { clearTimeout(timer); request.current++; }; }, [connection.baseUrl, connection.protocol, key]);
  function addModels(items: Array<{ id: string; name?: string }>) {
    const additions = items.map(item => ({ ...item, id: item.id.trim() })).filter((item, index, all) => item.id && !existing.has(item.id) && all.findIndex(other => other.id === item.id) === index).map(item => blankModel(item.id, item.name));
    if (!additions.length) return;
    setModels(current => [...current, ...additions]); setSelectedId(additions[0].id); if (!defaultId) setDefaultId(additions[0].id); setSelectedCatalog([]); setFormError('');
  }
  function addManual() { if (!manualId.trim()) return; if (existing.has(manualId.trim())) { setSelectedId(manualId.trim()); setFormError(t('This model is already in the gateway.', '此模型已添加到网关。')); return; } addModels([{ id: manualId }]); setManualId(''); }
  function updateModel<K extends keyof GatewayModel>(name: K, next: GatewayModel[K]) { setModels(current => current.map(model => model.id === selectedId ? { ...model, [name]: next } : model)); setFormError(''); }
  function removeModel(id: string) { const next = models.filter(model => model.id !== id); setModels(next); if (defaultId === id) setDefaultId(next[0]?.id || ''); if (selectedId === id) setSelectedId(next[0]?.id || ''); }
  function setMapping(level: ThinkingLevel, providerValue: string) { if (!active) return; const next = { ...active.effortMap }; if (providerValue.trim()) next[level] = providerValue.trim(); else delete next[level]; updateModel('effortMap', next); }
  async function save() {
    if (!models.length) { setFormError(t('Add at least one model before saving.', '至少添加一个模型后再保存。')); return; }
    const invalid = models.find(model => model.contextWindow < 1024 || model.contextWindow > 10000000 || model.maxTokens < 1 || model.maxTokens > model.contextWindow);
    if (invalid) { setSelectedId(invalid.id); setFormError(t('Check the context window and output limit for', '请检查此模型的上下文与输出上限：') + ' ' + invalid.id); return; }
    setBusy(true);
    const cleaned = models.map(model => { const effortMap = { ...model.effortMap }; if (connection.protocol === 'anthropic-messages' && !model.adaptiveThinking) for (const level of ['xhigh', 'max', 'ultra'] as const) delete effortMap[level]; return { ...model, effortMap }; });
    const selectedDefault = cleaned.find(model => model.id === defaultId) || cleaned[0]; const { id: modelId, name: _modelName, ...capabilities } = selectedDefault;
    const result = await run(async () => { await api.saveGateway({ ...connection, name: connection.name.trim(), baseUrl: connection.baseUrl.trim(), modelId, ...capabilities, models: cleaned }, key || undefined); return true; }, t('Gateway saved', '网关已保存'));
    setBusy(false); if (result) onClose();
  }
  return <Modal title={gateway ? t('Edit gateway', '编辑网关') : t('Connect a model gateway', '连接模型网关')} onClose={() => { if (!busy) onClose(); }} className="gateway-modal gateway-multi-modal">
    <p className="modal-intro">{t('One connection, multiple models. Add the models you want and configure each separately.', '一个连接，多个模型。添加需要的模型，再分别调整配置。')}</p>
    <form onSubmit={event => { event.preventDefault(); void save(); }}><fieldset disabled={busy} className="gateway-form-fields">
      <div className="form-grid"><Field label={t('Gateway name', '网关名称')}><input autoFocus required value={connection.name} onChange={event => setConnection(current => ({ ...current, name: event.target.value }))} placeholder={t('My gateway', '我的网关')} /></Field><Field label={t('API protocol', 'API 协议')}><select value={connection.protocol} onChange={event => setConnection(current => ({ ...current, protocol: event.target.value as Gateway['protocol'] }))}><option value="openai-completions">OpenAI Chat Completions</option><option value="openai-responses">OpenAI Responses</option><option value="anthropic-messages">Anthropic Messages</option></select></Field></div>
      <div className="form-grid gateway-connection-grid"><Field label="Base URL" hint={connection.protocol === 'anthropic-messages' ? t('Service origin without /v1.', '填写不含 /v1 的服务地址。') : t('API root, usually ending in /v1.', '填写 API 根路径，通常以 /v1 结尾。')}><input type="url" required value={connection.baseUrl} onChange={event => setConnection(current => ({ ...current, baseUrl: event.target.value }))} placeholder="https://your-gateway.example/v1" spellCheck={false} /></Field><Field label="API key" hint={gateway?.hasKey ? t('Leave blank to keep the saved key.', '留空则保留已保存的密钥。') : t('Shared by all models in this gateway.', '此网关下所有模型共用此密钥。')}><input type="password" required={!gateway?.hasKey} autoComplete="off" spellCheck={false} value={key} onChange={event => setKey(event.target.value)} placeholder={gateway?.hasKey ? '••••••••••••••••' : t('Enter your API key', '输入 API 密钥')} /></Field></div>
      <section className="gateway-model-section" aria-label={t('Gateway models', '网关模型')}>
        <div className="model-discovery-heading"><h3>{t('Models', '模型')} <span className="badge">{models.length}</span></h3><button type="button" className="button small" aria-expanded={catalogOpen} onClick={() => setCatalogOpen(!catalogOpen)}><Plus size={14} />{t('Add models', '添加模型')}<ChevronDown size={13} className={catalogOpen ? 'rotated' : ''} /></button></div>
        {catalogOpen && <div className="gateway-catalog">
          <div className="gateway-catalog-tools"><label className="model-menu-search"><Search size={15} /><input aria-label={t('Search available models', '搜索可用模型')} value={query} onChange={event => setQuery(event.target.value)} placeholder={t('Search available models', '搜索可用模型')} /></label><button type="button" className="text-button" disabled={fetching || !validConnection} onClick={() => void fetchModels()}><RefreshCw size={13} className={fetching ? 'spinning' : ''} />{t('Refresh models', '刷新模型列表')}</button></div>
          <div className="model-discovery-status" role="status">{fetching ? <><LoaderCircle size={13} className="spinning" />{t('Reading available models…', '正在读取可用模型…')}</> : modelError ? <span className="model-discovery-error">{modelError}</span> : loaded ? `${catalog.length} ${t('available models · select multiple to add', '个可用模型 · 可多选添加')}` : t('The list loads after the URL and key are ready.', '连接地址和密钥填好后会自动读取列表。')}</div>
          {!!shownCatalog.length && <div className="gateway-catalog-list">{shownCatalog.map(model => <label key={model.id} className={existing.has(model.id) ? 'already-added' : ''}><input type="checkbox" aria-label={`${t('Select model', '选择模型')} ${model.id}`} checked={existing.has(model.id) || selectedCatalog.includes(model.id)} disabled={existing.has(model.id)} onChange={event => setSelectedCatalog(current => event.target.checked ? [...current, model.id] : current.filter(id => id !== model.id))} /><span title={model.id}>{model.name || model.id}{model.name && model.name !== model.id && <small>{model.id}</small>}</span>{existing.has(model.id) && <small>{t('Added', '已添加')}</small>}</label>)}</div>}
          {loaded && !shownCatalog.length && <p className="model-menu-empty">{t('No matches. Add a model ID manually below.', '没有匹配项，可在下方手动添加模型 ID。')}</p>}
          <div className="gateway-catalog-actions"><button type="button" className="text-button" disabled={!shownCatalog.some(model => !existing.has(model.id))} onClick={() => setSelectedCatalog(current => [...new Set([...current, ...shownCatalog.filter(model => !existing.has(model.id)).map(model => model.id)])])}>{t('Select visible models', '选择当前结果')}</button><button type="button" className="button small primary" disabled={!selectedCatalog.length} onClick={() => { addModels(catalog.filter(model => selectedCatalog.includes(model.id))); setCatalogOpen(false); }}>{t('Add selected', '添加所选模型')}{selectedCatalog.length > 0 && ` (${selectedCatalog.length})`}</button></div>
          <div className="gateway-manual-add"><input aria-label={t('Model ID', '模型 ID')} value={manualId} onChange={event => setManualId(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); addManual(); } }} placeholder={t('Or enter a model ID manually', '也可以手动输入模型 ID')} spellCheck={false} /><button type="button" className="button small" disabled={!manualId.trim()} onClick={addManual}><Plus size={14} />{t('Add model ID', '添加模型 ID')}</button></div>
        </div>}
        {models.length > 0 ? <div className="gateway-model-workspace"><div className="gateway-model-navigation" aria-label={t('Added models', '已添加模型')}>{models.map(model => <button type="button" key={model.id} className={`gateway-model-tab ${model.id === selectedId ? 'active' : ''}`} aria-pressed={model.id === selectedId} onClick={() => setSelectedId(model.id)}><span><strong title={model.id}>{model.name || model.id}</strong>{model.name && model.name !== model.id && <small>{model.id}</small>}<small>{model.id === defaultId ? t('Default model', '默认模型') : `${model.contextWindow >= 1000000 ? '1M' : `${model.contextWindow / 1000}K`} · ${model.reasoning ? t('Reasoning', '推理') : t('Standard', '标准')}`}</small></span>{model.id === defaultId && <Star size={13} fill="currentColor" />}</button>)}</div>
          {active && <div className="gateway-model-detail"><div className="gateway-model-detail-heading"><h4 title={active.id}>{active.id}</h4><button type="button" className="text-button" disabled={defaultId === active.id} onClick={() => setDefaultId(active.id)}><Star size={13} fill={defaultId === active.id ? 'currentColor' : 'none'} />{defaultId === active.id ? t('Default', '默认') : t('Set default', '设为默认')}</button><IconButton label={`${t('Remove model', '移除模型')} ${active.id}`} onClick={() => removeModel(active.id)}><Trash2 size={15} /></IconButton></div>
            <Field label={t('Display name (optional)', '显示名称（可选）')}><input value={active.name || ''} onChange={event => updateModel('name', event.target.value)} placeholder={active.id} /></Field>
    <div className="form-grid"><div className="context-window-field"><Field label={t('Context window (tokens)', '上下文窗口（Token）')}><input aria-label={t('Context window (tokens)', '上下文窗口（Token）')} aria-describedby="context-window-hint" type="number" min={1024} max={10000000} required value={active.contextWindow} onChange={event => updateModel('contextWindow', Number(event.target.value))} /></Field><div className="context-presets" role="group" aria-label={t('Context window presets', '上下文窗口预设')}>{[300000, 500000, 1000000].map(size => <button key={size} type="button" aria-pressed={active.contextWindow === size} onClick={() => updateModel('contextWindow', size)}>{size === 1000000 ? '1M' : `${size / 1000}K`}</button>)}</div><small id="context-window-hint">{t('The conversation compacts automatically near 90% of this window.', '对话接近窗口的 90% 时自动压缩。')}</small></div><Field label={t('Maximum output tokens', '最大输出 Token')} hint={t('Reasoning and the answer share this limit.', '思考与正文共用这个上限。')}><input type="number" min={1} max={active.contextWindow} required value={active.maxTokens} onChange={event => updateModel('maxTokens', Number(event.target.value))} /></Field></div>
    <details className="reasoning-capabilities model-pricing"><summary><span>{t('Usage pricing', '用量单价')}</span><ChevronDown size={14} /></summary><label className="checkbox-row"><input type="checkbox" checked={!!active.pricing} onChange={event => updateModel('pricing', event.target.checked ? { currency: 'USD', input: 0, output: 0, cacheRead: 0, cacheWrite: 0 } : undefined)} /><span>{t('Configure model rates', '配置模型单价')}</span></label>{active.pricing && <><p>{t('Rates per one million tokens. Use the same currency across squad models for a comparable cost budget.', '每 100 万 Token 的价格。小队模型请使用相同币种，便于统一计算金额预算。')}</p><Field label={t('Currency', '币种')}><input maxLength={3} value={active.pricing.currency} onChange={event => updateModel('pricing', { ...active.pricing!, currency: event.target.value.toUpperCase() })} /></Field><div className="form-grid">{([{ key: 'input', label: t('Input', '输入') }, { key: 'output', label: t('Output', '输出') }, { key: 'cacheRead', label: t('Cache read', '缓存读取') }, { key: 'cacheWrite', label: t('Cache write', '缓存写入') }] as const).map(item => <Field key={item.key} label={item.label}><input type="number" min={0} step="any" value={active.pricing![item.key]} onChange={event => updateModel('pricing', { ...active.pricing!, [item.key]: Number(event.target.value) })} /></Field>)}</div></>}</details>
    <label className="checkbox-row"><input type="checkbox" checked={active.reasoning} onChange={event => updateModel('reasoning', event.target.checked)} /><span>{t('This model supports reasoning', '此模型支持推理')}<small>{t('Enables the effort control in conversations.', '在对话中启用思考强度控制。')}</small></span></label>
    {active.reasoning && <details className="reasoning-capabilities"><summary><span>{t('Reasoning capabilities', '思考强度能力')}</span><ChevronDown size={14} /></summary><p>{t('Defaults: low / medium / high / xhigh / max / max. Ultra also enables coordinated agent squads. Ultra is fixed to max; other values can be adjusted for your gateway.', '默认值为 low / medium / high / xhigh / max / max。Ultra 固定使用 max 并启用子代理小队；其余档位可按网关调整。')}</p>{connection.protocol === 'anthropic-messages' && <label className="checkbox-row"><input type="checkbox" checked={!!active.adaptiveThinking} onChange={event => updateModel('adaptiveThinking', event.target.checked)} /><span>{t('Adaptive thinking', '自适应思考')}<small>{t('Required for the additional effort levels on this protocol.', '此协议使用更高强度时需要启用。')}</small></span></label>}<div className="effort-mapping-grid">{thinkingLevels.map(level => <Field key={level} label={thinkingLabel(level, t)}><input aria-label={`${thinkingLabel(level, t)} ${t('provider value', '网关参数值')}`} value={level === 'ultra' ? 'max' : active.effortMap?.[level] ?? ''} readOnly={level === 'ultra'} title={level === 'ultra' ? t('Ultra uses max reasoning and adds a coordinated agent squad.', 'Ultra 固定使用 max，并增加主代理统筹的子代理小队。') : undefined} placeholder={level === 'ultra' ? 'max' : level} disabled={['xhigh', 'max', 'ultra'].includes(level) && connection.protocol === 'anthropic-messages' && !active.adaptiveThinking} onChange={event => setMapping(level, event.target.value)} /></Field>)}</div></details>}
    <label className="checkbox-row"><input type="checkbox" checked={!!active.nativeSearch?.enabled} onChange={event => updateModel('nativeSearch', { ...active.nativeSearch, enabled: event.target.checked })} /><span>{t('This model supports native web search', '此模型支持原生联网搜索')}<small>{t('Reuses this connection’s API key on compatible gateways.', '在兼容网关上复用此连接的 API 密钥。')}</small></span></label>{active.nativeSearch?.enabled && <Field label={t('Responses endpoint override (optional)', 'Responses 端点覆盖（可选）')} hint={t('Must use the same origin as the gateway URL.', '必须与网关地址同源。')}><input type="url" value={active.nativeSearch.responsesUrl || ''} onChange={event => updateModel('nativeSearch', { enabled: true, responsesUrl: event.target.value })} placeholder="https://your-gateway.example/v1/responses" spellCheck={false} /></Field>}
          </div>}
        </div> : <div className="gateway-model-empty">{t('Add models from the list above, or enter a model ID.', '从上方列表添加模型，也可以手动填写模型 ID。')}</div>}
      </section>
      {formError && <p className="gateway-form-error" role="alert">{formError}</p>}
      <div className="modal-actions gateway-save-actions"><span>{models.length} {t('models · one shared connection', '个模型 · 共用一个连接')}</span><button type="button" className="button" onClick={onClose}>{t('Cancel', '取消')}</button><button className="button primary" disabled={!models.length}>{busy ? t('Saving…', '保存中…') : t('Save gateway', '保存网关')}</button></div>
    </fieldset></form>
  </Modal>;
}
