import { useState } from 'react';
import { BookOpen, Folder, FolderPlus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { useApp } from './context';
import { IconButton, Toggle } from './primitives';

export function SkillSettings() {
  const { data, api, run, t } = useApp();
  const [query, setQuery] = useState(''); const [refreshing, setRefreshing] = useState(false); const [pending, setPending] = useState<string[]>([]);
  const [scope, setScope] = useState('all');
  const skills = data.skills.filter(skill => (scope === 'all' || (scope === 'global' ? !skill.projectId : skill.projectId === scope)) && `${skill.name} ${skill.description}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const sourceName = (source?: string) => source === 'project' ? t('Project', '项目') : source === 'custom' ? t('Added folder', '添加的目录') : source === 'bundled' ? t('Cardwright', 'Cardwright') : t('Local account', '本地账户');
  async function refresh() { setRefreshing(true); await run(() => api.refreshSkills()); setRefreshing(false); }
  async function add() { await run(async () => { const path = await api.pickSkillFolder(); if (path) await api.savePreferences({ skillPaths: [...new Set([...data.preferences.skillPaths, path])] }); }); }
  return <><div className="section-heading"><div><h3>{t('Your skill library', '你的技能库')}</h3><p>{t('Cardwright discovers local skills automatically. Enabled skills can be chosen by the agent or invoked with / in a conversation.', 'Cardwright 会自动发现本地技能。已启用的技能可由 Agent 按任务选用，也可以在对话中输入 / 调用。')}</p></div><IconButton label={t('Refresh skills', '刷新技能')} disabled={refreshing} onClick={() => void refresh()}><RefreshCw size={18} className={refreshing ? 'spinning' : ''} /></IconButton></div>
    <div className="skill-library-toolbar"><div className="skill-search"><Search size={16} /><input aria-label={t('Find a skill', '搜索技能')} placeholder={t('Find a skill…', '搜索技能…')} value={query} onChange={event => setQuery(event.target.value)} /></div><select aria-label={t('Skill source', '技能来源')} value={scope} onChange={event => setScope(event.target.value)}><option value="all">{t('All sources', '所有来源')}</option><option value="global">{t('Shared skills', '全局技能')}</option>{data.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><button className="button small" onClick={() => void add()}><FolderPlus size={15} />{t('Add folder', '添加目录')}</button></div>
    <p className="skill-discovery-note">{t('Searches .agents/skills, .codex/skills and .claude/skills in your home and project folders. Changes apply to the next run.', '自动读取用户目录和项目中的 .agents/skills、.codex/skills 与 .claude/skills。启用状态的更改在下一轮运行生效。')}</p>
    {data.preferences.skillPaths.length > 0 && <details className="skill-folder-details"><summary>{t('Additional skill folders', '额外技能目录')} <span>{data.preferences.skillPaths.length}</span></summary><div className="skill-paths">{data.preferences.skillPaths.map(path => <div key={path}><button className="path-button" onClick={() => void run(() => api.openPath(path))}><Folder size={14} /><span>{path}</span></button><IconButton label={`${t('Remove skill folder', '移除技能文件夹')} ${path}`} onClick={() => void run(() => api.savePreferences({ skillPaths: data.preferences.skillPaths.filter(p => p !== path) }))}><Trash2 size={14} /></IconButton></div>)}</div></details>}
    <div className="skill-library-count">{skills.length} {t('skills', '个技能')}<span>{data.skills.filter(skill => skill.enabled !== false && !skill.shadowedBy).length} {t('enabled', '已启用')}</span></div>
    {skills.length ? <div className="skill-library">{skills.map(skill => { const id = skill.id || skill.path; return <article className={`skill-library-row ${skill.enabled === false ? 'is-disabled' : ''}`} key={`${id}-${skill.projectId || 'global'}`}><BookOpen size={18} /><div className="skill-library-copy"><div className="skill-title"><button onClick={() => void run(() => api.openPath(skill.path))}>{skill.name}</button><span>{sourceName(skill.source)}{skill.projectId ? ` · ${data.projects.find(project => project.id === skill.projectId)?.name || ''}` : ''}</span></div><p>{skill.description}</p><div className="skill-state">{skill.shadowedBy ? t('A higher-priority skill with this name is selected.', '同名技能已有更高优先级的版本。') : skill.enabled === false ? t('Disabled · not available to agents or slash commands', '已停用 · Agent 和斜杠命令均不会使用') : skill.disableModelInvocation ? t('Manual only · invoke with a slash command', '仅手动调用 · 使用斜杠命令发起') : t('Automatic selection + slash command', '自动选用 + 斜杠调用')}</div></div><Toggle label={`${t('Enable skill', '启用技能')} ${skill.name}`} checked={skill.enabled !== false} disabled={pending.includes(id)} onChange={enabled => { setPending(current => [...current, id]); void run(() => api.setSkillEnabled(id, enabled)).finally(() => setPending(current => current.filter(item => item !== id))); }} /></article>; })}</div> : <div className="skill-library-empty"><BookOpen size={24} /><p>{query ? t('No skills match this search.', '没有匹配的技能。') : t('No skills found here yet. Add a skill folder or refresh after creating a SKILL.md file.', '暂未发现技能。添加技能目录，或创建 SKILL.md 后刷新。')}</p></div>}
  </>;
}
